### ISSUE TITLE
Need new icon

### ISSUE THREAD

**Issue by phase1geo** [phase1geo/Outliner#1]
Outliner needs a new icon that will work well in elementary.

**Comment by phase1geo** [comment]
@fatih20 Would you be able and willing to create a more suitable icon? Outliner will be a new outlining application for elementary. It is both a standalone application and a companion application for the mind-mapping application, Minder. I like the basic idea of the current icon shape (while Minder is more about ideating hence the thought cloud shape of the icon, Outliner is more about communicating ideas hence the speech bubble shape). However, I don’t care for the icon proportions and lack of elementary styling.

Could you help me out?

**Comment by Fatih20** [comment]
Yes, but I should know what this app is for.

**Comment by phase1geo** [comment]
If you know what outlining is in the context of writing, it is an application that allows you to quickly create, edit, and rearrange an outline and then export that outline in many different formats. You can also import a mind-map, converting it into an outline.

**Comment by Fatih20** [comment]
What's an outline?

**Comment by phase1geo** [comment]
An example would be the following:

I. Introduction
    A. Catchy beginning sentence.
    B. Lead in to main material
II. Main idea
    A. Description of problem
        1. Problem 1
        2. Problem 2
        3. Problem 3
    B. Description of solution
III. Conclusion

**Comment by phase1geo** [comment]
My example lost indentation when I clicked on the Comment button.

**Comment by phase1geo** [comment]
```
I. Introduction
    A. Catchy beginning sentence.
    B. Lead in to main material
II. Main idea
    A. Description of problem
        1. Problem 1
        2. Problem 2
        3. Problem 3
    B. Description of solution
III. Conclusion
```

**Comment by phase1geo** [comment]
Much better

**Comment by Fatih20** [comment]
I'll get on it.

**Comment by phase1geo** [comment]
👍

**Comment by phase1geo** [comment]
I'm getting pretty close to creating the initial release now (perhaps a week or so away at this point).

**Comment by Fatih20** [comment]
I'll advise you to fix the minder bug first before doing this.

**Comment by phase1geo** [comment]
Noted.

**Comment by phase1geo** [comment]
I have merged the pull request with the new icons.  Thanks @Fatih20!
