### ISSUE TITLE
Not in AppCenter?

### ISSUE THREAD

**Issue by jaslar** [phase1geo/Outliner#11]
I got excited about this one, and clicked on the AppCenter link -- but it's not there. I've sudo apt update/upgraded, and no sign of it. Is the app on its way there? Is there something else I, an elementaryOS user, need to do to get it?

I'm trying to "download zip" clone, but I'm a git newbie.

**Comment by phase1geo** [comment]
It's been pending AppCenter approval for a while, rejected twice now with fix requests. So it's not in AppCenter yet.  Hang tight!
