### ISSUE TITLE
Add enhanced functionality to row disclosure keyboard shortcut

### ISSUE THREAD

**Issue by phase1geo** [phase1geo/Outliner#17]
If the right-arrow button is entered when a row is selected which has other rows within it, the current functionality causes all descendent rows to be shown.

An enhancement to this functionality would be to allow the user to only disclose a single level at a time. (Example: the first press opens a single level, another press will open the next level and so on).

We would also implement closing a single level at a time. And we would add another way to open/close an entire subtree in one keystroke.

**Comment by phase1geo** [comment]
This feature has been implemented in the development branch and will be generally accessible in the upcoming 1.3 stable release.

**Comment by jaslar** [comment]
Works a treat! Love this one.
