### ISSUE TITLE
Display bug when changing theme and switching tabs

### ISSUE THREAD

**Issue by NathanBnm** [phase1geo/Outliner#20]
I have the following issue when switching tabs after changing the theme:

![Enregistrement d'écran depuis 2020-04-11 12 52 17](https://user-images.githubusercontent.com/45366162/79041876-8103ca00-7bf3-11ea-83cd-31704cd2e5c8.gif)

I was wondering if you could apply the selected theme to tabs too, like in elementary Code (maybe you can take a look):

![image](https://user-images.githubusercontent.com/45366162/79041897-9e389880-7bf3-11ea-9598-6aa374c7b6b3.png)

**Comment by phase1geo** [comment]
This issue should be fixed in the development version of Outliner and will be generally available in the next stable release coming soon.

**Comment by NathanBnm** [comment]
@phase1geo I just tested on my side and it seems that you didn't completely fixed it but partially.

I mean instead of all the background not being updated, now there is just the focused item which keeps the old theme as following:

![Enregistrement d'écran depuis 2020-04-12 10 24 03](https://user-images.githubusercontent.com/45366162/79064330-4a3bbb80-7ca8-11ea-87b7-474adefb116e.gif)

Moreover the last used theme is in preferences in order to use this one when opening a new tab.

And as I said, what about colouring the tabs too?

**Comment by phase1geo** [comment]
I will take a look.

Changing the look of the tabs is probably a good idea although this is a feature request that I would like to track with a separate issue.

**Comment by phase1geo** [comment]
I have updated the development branch to add support for colorizing the tab bar to match the current canvas background color.

I still need to look into the persistent theming issue.

**Comment by NathanBnm** [comment]
This is really better

**Comment by phase1geo** [comment]
I'm not able to recreate the theming issue related to switching tabs. Can you still see this issue on your end with the latest version of the development branch?

**Comment by NathanBnm** [comment]
@phase1geo this seems to be fixed now :D Closing this.
