### ISSUE TITLE
White border at first launch

### ISSUE THREAD

**Issue by NathanBnm** [phase1geo/Outliner#21]
When launching the windows for the first time there is a white border around the editing zone:

![image](https://user-images.githubusercontent.com/45366162/79064230-6ee36380-7ca7-11ea-88b7-1406ff65c43a.png)

But there's not anymore after switching theme or when opening a new tab:

![image](https://user-images.githubusercontent.com/45366162/79064244-8c183200-7ca7-11ea-97a2-0f999dba80f1.png)

I'm running the development version.

**Comment by phase1geo** [comment]
I can't seem to replicate this issue. Could you grab the latest development branch and see if it still persists?

**Comment by NathanBnm** [comment]
@phase1geo it's fixed now :smile: Closing this.
