### ISSUE TITLE
Overlap when increasing title size after adding some notes

### ISSUE THREAD

**Issue by NathanBnm** [phase1geo/Outliner#24]
See the following screenshot:
![image](https://user-images.githubusercontent.com/45366162/79065166-735f4a80-7cae-11ea-8ec1-c17d9e43eb6b.png)

First row: I increased the title size (`<H1>`) before adding a note
Second row: I increased the title size (`<H1>`) after adding a note

I'm running the development version.

**Comment by phase1geo** [comment]
This issue should be fixed in the development version and will be generally available in the next stable release.

**Comment by NathanBnm** [comment]
It's working fine now :smile: Closing this.
