### ISSUE TITLE
Selecting a row is very hard

### ISSUE THREAD

**Issue by NathanBnm** [phase1geo/Outliner#25]
I have a lot of trouble selecting a row in to move it or to right-click and open the context menu.

It always moves by accident (and makes #23) or it doesn't open the context menu but select the text editor instead.

It seems that selecting/right-clicking a row is possible on the very left zone only.

I'm running the development version.

**Comment by phase1geo** [comment]
By default, left-clicking a row will place the row into edit mode, placing the cursor at the selected spot. You can either hit the escape key immediately or use the left side of the row for selecting the row for action as you have mentioned.
