### ISSUE TITLE
Make shortcuts cheatset window translatable

### ISSUE THREAD

**Issue by NathanBnm** [phase1geo/Outliner#27]
For now it isn't because you're using a `.ui` file, don't know how to manage this for translation.

**Comment by phase1geo** [comment]
I have updated the development branch to include shortcuts.ui translation generation.

**Comment by NathanBnm** [comment]
@phase1geo I don't understand why you added this line to `meson.build`

 ```meson.build
join_paths(meson.source_root(), 'data', meson.project_name()+'.shortcuts.ui'),
```

This is breaking translations, because it's adding a relative path into the `po` files. And it's duplicated between main and extra translations.
