### ISSUE TITLE
Shortcuts cheatset translation does not work

### ISSUE THREAD

**Issue by NathanBnm** [phase1geo/Outliner#30]
It seems that translations are not applying. I think the `shortcuts.ui` file is installed without being translated. What about using `i18n.merge_file()` like for desktop and appdata translations?

Don't know if this kind of file can be properly translated.

Related to #27

**Comment by phase1geo** [comment]
According to the Valadoc documentation for GtkBuilder they are supposed to be translated with gettext for items with the translatable attribute set to true.

**Comment by phase1geo** [comment]
It’s a common way to create UIs (Glade supports it) with Gtk so Iwould be surprised if it didn’t support translations. It is also the only way to create shortcut windows using the standard tooling.

**Comment by NathanBnm** [comment]
I agree but I didn't see anywhere how to translate them properly with meson integration 🤔 I tried to build the app with translated shortcuts but it doesn't work. New translations are loaded becauser "Header" (the tooltip I added) is translated.

**Comment by phase1geo** [comment]
I believe I have things working in the development branch now. I needed to remove the translation files from the extra directory and move them to the po directory. I then set the domain attribute in the shortcuts.ui file and now things are looking good if I set my language to French in system preferences.

**Comment by NathanBnm** [comment]
This is working fine now! Closing this.
