### ISSUE TITLE
Discussion about translations

### ISSUE THREAD

**Issue by NathanBnm** [phase1geo/Outliner#31]
@phase1geo could what does the following strings stands for? I don't understand where they can appear in the app, and why they are in lowercase:

```po
#: src/undo_actions/UndoTextTagRemove.vala:31
msgid "format tag remove"
msgstr ""

#: src/undo_actions/UndoTextDelete.vala:30
msgid "text deletion"
msgstr ""

#: src/undo_actions/UndoNodeExpander.vala:29
msgid "expander change"
msgstr ""

#: src/undo_actions/UndoNodeInsert.vala:30
msgid "insert item"
msgstr ""

#: src/undo_actions/UndoNodeName.vala:30
msgid "title change"
msgstr ""

#: src/undo_actions/UndoTextReplace.vala:31
msgid "text replacement"
msgstr ""

#: src/undo_actions/UndoNodeNote.vala:30
msgid "note change"
msgstr ""

#: src/undo_actions/UndoNodeMove.vala:32
msgid "move item"
msgstr ""

#: src/undo_actions/UndoNodeIndent.vala:28
msgid "indent item"
msgstr ""

#: src/undo_actions/UndoTextTagAdd.vala:31
msgid "format tag add"
msgstr ""

#: src/undo_actions/UndoTextInsert.vala:29
msgid "text insertion"
msgstr ""

#: src/undo_actions/UndoReplaceAll.vala:47
msgid "replace all"
msgstr ""

#: src/undo_actions/UndoNodePaste.vala:30
msgid "paste item"
msgstr ""

#: src/undo_actions/UndoNodeDelete.vala:30
msgid "delete item"
msgstr ""

#: src/undo_actions/UndoNodeUnindent.vala:28
msgid "unindent item"
msgstr ""

#: src/undo_actions/UndoNodeCut.vala:30
msgid "cut item"
msgstr ""

#: src/undo_actions/UndoNodeSplit.vala:32
msgid "split item"
msgstr ""
```

_Originally posted by @NathanBnm in https://github.com/phase1geo/Outliner/pull/19#issuecomment-612583726_

**Comment by NathanBnm** [comment]
I was wondering too if it would be possible to translate the default filename `unamed%d.outliner`?

**Comment by phase1geo** [comment]
Those strings are appended to the Undo/Redo strings in the Undo/Redo button tooltips.

**Comment by phase1geo** [comment]
As far as translating the default filename string, I wouldn't have an issue with the "unnamed" portion of the string, but the .outliner extension will need to be there. I'll make a check-in.

**Comment by phase1geo** [comment]
The default filename has been changed in the code and I have regenerated the translation files.

**Comment by NathanBnm** [comment]
> Those strings are appended to the Undo/Redo strings in the Undo/Redo button tooltips.

There is actually a display issue with this, I'm opening  #32

**Comment by NathanBnm** [comment]
> The default filename has been changed in the code and I have regenerated the translation files.

Is is possible to put spaces in the filename? For example in French, "unnamed" means "sans nom".

**Comment by phase1geo** [comment]
It should be fine to have spaces in names.
