### ISSUE TITLE
Display issue on Undo/Redo actions

### ISSUE THREAD

**Issue by NathanBnm** [phase1geo/Outliner#32]
See the following screenshot:

![image](https://user-images.githubusercontent.com/45366162/79336900-d4905380-7f24-11ea-94b0-6e82ecf4962d.png)

What about adding parenthesis or quotes? For a better localization.

**Comment by phase1geo** [comment]
This sounds like a good idea. I'm going to try using parenthesis first and see what that looks like.

**Comment by phase1geo** [comment]
I have updated the development branch to add a ": " in-between the Undo/Redo string and the description string. Hopefully, this format is suitable for translations.

**Comment by NathanBnm** [comment]
> I have updated the development branch to add a ": " in-between the Undo/Redo string and the description string. Hopefully, this format is suitable for translations.

Sure this is better! Please just do not forget to include the semicolon in translations as I explained in #34
