### ISSUE TITLE
Support clone nodes

### ISSUE THREAD

**Issue by waldyrious** [phase1geo/Outliner#4]
I've been looking for an outliner that is able to show a subtree in more than one place (so that an edit to the clone will be reflected in the original item as well) but most of the popular outliners out there (Workflowy, Dynalist, Checkvist, OrgMode, etc.) do not support this feature. The technical name for this seems to be [transclusion](https://en.wikipedia.org/wiki/Transclusion), by the way.

The only outliners I found with this capability are the [Leo editor](http://leoeditor.com/) and [Trilium notes](https://github.com/zadam/trilium#readme). The latter has a nice [wiki page](https://github.com/zadam/trilium/wiki/Cloning-notes) explaining the motivation for this feature. Unfortunately, both use a [two-pane layout](https://en.wikipedia.org/wiki/Outliner#Layout) (i.e. they show the outline in a sidebar and the content of the selected item in the main pane), and are generally more complex and less intuitive to use than the "collapsible bullet list" outliners.

I'd love if the Outliner app could incorporate this feature!

**Comment by phase1geo** [comment]
Sounds like an interesting feature! I will consider getting something like this integrated into the tool.

**Comment by phase1geo** [comment]
I have this feature implemented in the cloning2 development branch. I will eventually integrate this feature into the development branch when Outliner has been accepted to elementary AppCenter.

**Comment by phase1geo** [comment]
I have merged the `cloning2` branch into the `devel` branch.

**Comment by waldyrious** [comment]
Now that I am able to build the app locally (#5), I tried checking out the `cloning2` branch and launching the application with `./app run`, but I see no way to clone the nodes. Is there a keyboard shortcut or some other way to do it?

**Comment by phase1geo** [comment]
Select a row to clone, right click to bring up the contextual menu, select Clone. Then select the row to put the clone, right click, select the Paste as clone option. You can also unclone a selected row which is a clone by using the contextual menu and selecting Unclone.

**Comment by waldyrious** [comment]
Nice, just tried that and it works pretty well :) That was really quick btw!

I wonder if any of the outline formats supports this type of node — it would be nice to be able to export and import outlines that include clone nodes. I'll report back here if I find something about that.
