### ISSUE TITLE
adding checkbox state to rows not to all the outline

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Outliner#43]
When choosing to show checkboxes it appears throughout the outline and not just in the specific row

![2020-05-19_17-59](https://user-images.githubusercontent.com/13304792/82356376-5deee600-99fb-11ea-90d0-b17a88bd61c9.png)

**Comment by phase1geo** [comment]
That is the intended behavior. If you want to remove checkboxes, you can highlight a row and hit the ‘t’ key until the checkbox is removed. Doing the same for parent rows will have the effect of removing the parent and all descendant rows of the parent row.

**Comment by wada3n** [comment]
yep, It really works :)
I think this should be added to the shortcuts cheatsheet.

I am currently working on making a complete outline, as a documentation of the program, When I finish it, I upload it to you if you want to put it with the app as a starter.

**Comment by wada3n** [comment]
What do you think if the checkbox is placed on the far right, instead of placing it directly at the beginning of the rows, thus allowing more room in the interface, and allows the possibility of adding additional internal checkbox in the form of Markdown in the row and its children.
For the new checkbox, if finished, the row become in a slight gray color that shows the job is done.
The idea of​​ turning on/off checkbox remains in the preferences.

![Sélection_007](https://user-images.githubusercontent.com/13304792/82473968-3d3d9380-9ac2-11ea-8b6a-172e0d0c3ca4.png)

**Comment by phase1geo** [comment]
That sounds like a nice improvement idea.

For checkboxes, there is the concept of “not started” (empty box), “in progress“ (dashed box), and “done” (checked box). I’m assuming that items “in progress” would otherwise look the same as “not started” items. Do you agree?

**Comment by wada3n** [comment]
Absolutely yes.
The interface will always be clear.

**Comment by phase1geo** [comment]
I've decided to create a gsetting that will allow the user to change where checkboxes are located.  Either in the current location or to the right of the row.  Moving the checkboxes will help keep the left side cleaner from a UI perspective, as noted, but it also "flattens" the checkboxes losing the visual hierarchy.  Making it an option will at least allow this to be changed at some point, if desired.

**Comment by phase1geo** [comment]
I have the implementation completed in the development branch which will generally available in the next stable release.

**Comment by wada3n** [comment]
Very cool.
I just noticed a problem when choosing to enable Markdown highlighting, choose a text and then go back and disable it the Markdown option , the bar remains visible and does not disappear and so on.
![2020-05-30_22-12](https://user-images.githubusercontent.com/13304792/83339211-68df2b80-a2c3-11ea-82d4-4c31cc7b3d81.png)

I did not understand what is causing this problem, I tried this on Ubuntu 20.04 and elementary OS
