### ISSUE TITLE
Highlight the tree path 

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Outliner#45]
It will be very helpful for large outlines, and can be turned **off** or **on** in preferences.

like this picture:

![Screen Shot 2020-05-19 at 3 00 06 PM](https://user-images.githubusercontent.com/13304792/82371592-5981f780-9a12-11ea-97a7-c1002899b3ba.png)

**Comment by phase1geo** [comment]
I have an implementation checked into the devel branch that adds a document-specific option to turn on/off the depth lines. I may make a few enhancements before the next stable release, but if you want to try it out and let me know if you see any issues, feel free.

**Comment by wada3n** [comment]
Bonjour @phase1geo :)
Very cool, I have tried it, just what do you think about adding a small number underneath folded disclosure triangles indicates how many items are currently hidden.

![Sélection](https://user-images.githubusercontent.com/13304792/82472266-d5864900-9abf-11ea-8c63-b52d812ebad8.png)

**Comment by phase1geo** [comment]
The number of children is now being displayed in a tooltip if you hover over a collapsed row expander.

**Comment by phase1geo** [comment]
I have made a modification to the depth lines feature which changes how depth lines are displayed. Previously, depth lines where shown for each row for each level of depth.  I have checked in a change to the 'devel' branch which only displays a depth line is that level of depth has a sibling row below it.  I feel like this gives the depth line more meaning and can possibly reduce the number of lines drawn, making the outline feel cleaner; however, I'm not sure if this would break users' expectations of the feature compared to how it is used in other applications.

Could you try using the latest devel branch and let me know your thoughts on this change? I can easily switch it back to the previous version or I can even make it a gsetting where we will pick a sane default to use. Either way, I would appreciate your comments/feedback.

**Comment by wada3n** [comment]
The idea is excellent and has a good meaning, allowing more space to see away from distraction.
What I understood is that the line of depth appears only in rows with childrens and so on every time it is added indoors.
After reviewing the new version, I think if I am not mistaken, there is an error in the implementation, as I put the same motif duplicate and showed me a different behavior.

![2020-06-07_19-56](https://user-images.githubusercontent.com/13304792/83977594-94809800-a8f9-11ea-8829-7a9073e50950.png)


I think it is better to create special gsetting that will make more sense, that is, to divide the depth line into full or define it by level.

I appreciate more, the wonderful work you do

**Comment by wada3n** [comment]
hi @phase1geo 
Only now I realized the meaning of the new addition
There is no need for the depth line to appear as long as there is no other party under it, practically as long as there is no relative row below it, the depth is ultimately to the end.
You are right on both sides that the idea is very good but a little strange for a user coming from different behavior in similar apps.

What do you think instead of using gsetting, add to GtkPopover a separate window titled "advanced" in which to place new features
