### ISSUE TITLE
Outliner is not recognized as an application for opening .outliner files

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Outliner#50]
On Ubuntu 20.04, the app does not recognize .outliner files
In fact, it appears in the applications menu when you right-click on files, but after clicking on it nothing happens.

These are the outputs from terminal:
```bash
 com.github.phase1geo.outliner Hello.outliner 

(com.github.phase1geo.outliner:14441): GLib-GIO-CRITICAL **: 22:01:23.805: This application can not open files.
```

**Comment by wada3n** [comment]
Frankly, I don't know what I can do to help.
But I wonder why an option was designated to open a file, why is the application not left by default opening files with the extension designated for it?
Is not every time a new file is opened that is added to a new tab in the application?
is the problem in xml files With the added customization?

I would be glad to try out the new additions that you implement and it would be nice to come up with a good solution.
I wish you the best always.

**Comment by phase1geo** [comment]
I believe that I have this issue fixed in the devel branch which will be generally available in the next stable release.
