### ISSUE TITLE
AutoHide headerbar when typing

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Outliner#51]
What if optional settings are added for Headerbar AutoHide when typing
It will be very helpful for focus especially as Outliner is mainly for writing and individual brainstorming.

This is an example from Apostrophe Markdown Editor:
![Peek 2020-06-07 20-26](https://user-images.githubusercontent.com/13304792/83978137-55544600-a8fd-11ea-8147-2a50170126a6.gif)

**Comment by phase1geo** [comment]
I'll see what I can come up with. I don't like the idea of the header bar magically disappearing and reappearing as you are showing in the above application.  I think that most applications that provide this sort of "distraction free" writing experience generally have a button, menu item, and/or keyboard shortcut that puts them into the mode (possibly adding a fullscreen experience) and then interacting with something in the window (i.e., hitting Escape key, moving mouse cursor to top of window, etc.) that will exit the focus mode.  I think I like that idea much better.

**Comment by wada3n** [comment]
Well, the idea in the end is to reduce the distracting effects from the application in case of writing.
I think that the full screen mode will not be very appropriate because the application is inherently beautiful with other tiling windows, I always preferred to use it in part of the screen, but not the full screen way.
Your idea is very beautiful to customize a shortcut, and through it, the header bar and tab bar also disappear.
Thus, the entry is only in this case at the time of need, and at the choice of the user.
Greetings to you

**Comment by phase1geo** [comment]
Your point about fullscreen mode is understood.  Perhaps automatically going to fullscreen mode would be a preference option (the default would be leave the window size as is).

**Comment by wada3n** [comment]
I totally agree with this.

The next release deserves to be version 2 :)
It will be full of vitamins :)

**Comment by phase1geo** [comment]
Yes, this implementation is closer to what I had in mind.

**Comment by phase1geo** [comment]
I have implemented a solution that I am mostly happy with for this feature.  You can now hide the headerbar and tabbar by either clicking on the properties button in the header bar and selecting the "Enter Focus Mode" option or using the keyboard shortcut F2 to enter focus mode.  Use the same keyboard shortcut to exit focused writing mode or click on the exit button in the upper right corner of the outline.

I have checked in the changes to the devel branch which will be generally available in the next stable release.

**Comment by wada3n** [comment]
That's cool, that's what I've been waiting for!
