### ISSUE TITLE
Crashes when I try to highlight text from left to right

### ISSUE THREAD

**Issue by stepiend** [phase1geo/Outliner#52]
When I click on the text and move cursor from left to right while holding the mouse button Outliner crashes and every change made to the document during current session is lost. It doesn't happen when I do it from right to left. At the beginning I needed to move mouse quite far, but now it happens after barely noticeable movement, so even it crashes when I accidentally click left mouse button.

**Comment by phase1geo** [comment]
Is this a problem with version 1.2.0?

If you are able, could you try running Outliner from the latest version of the 'devel' branch and see if you can get it fail in the same way? I just attempted to replicate the issue with the latest devel branch and was unable to get it to fail.

**Comment by stepiend** [comment]
Currently I'm not able to replicate it either, even though yesterday it crashed consistently.

**Comment by phase1geo** [comment]
I have marked this issue as "Unable to reproduce". I will leave the issue open for the time being, so if you or someone else finds a way to replicate this issue, feel free to update this bug report.

**Comment by phase1geo** [comment]
I am going to go ahead and close out this issue as it cannot be reproduced.  If this issue occurs with version 1.3.0 or later, feel free to reopen this issue or open a new issue.
