### ISSUE TITLE
Suggestion - manual save button

### ISSUE THREAD

**Issue by stepiend** [phase1geo/Outliner#53]
Sometimes I want to save the text I am working with to the file and then I need to go to 'save file as' button, select the file and delete manually '.outliner' from the name. In my opinion program should automatically detect if name string ends with '.outliner' and then do not add it to the name for the second time. Moreover the 'save' button would make working with Outliner much more pleasant.

**Comment by phase1geo** [comment]
Outliner automatically saves in the background, so only the Sava As is needed for changing the name of the file you want to save to.

I will look into the other suggestion, however.

**Comment by phase1geo** [comment]
I have fixed the issue of not detecting the .outliner extension of a selected file in the Save As window which would lead to a file containing two .outliner extensions on a filename.  This fix is available in the 'devel' branch and will be generally available in the next stable release of Outliner.

**Comment by stepiend** [comment]
The problem is that when app crashes then autosave seems not to work and your work is reset to the state from before current session but if you manually save before app crash than everything is saved correctly.

**Comment by phase1geo** [comment]
You can always use the keyboard shortcut Control-S to manually save. However, the application crashing is what I am most concerned about. Have you submitted an issue for that?

**Comment by stepiend** [comment]
Yes, I have

**Comment by phase1geo** [comment]
Ah, very good.
