### ISSUE TITLE
The selected row remains visible when you press Hide Rows

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Outliner#54]
There is a problem that occurs while hiding the children of a row, where in the case of choosing one of the internal rows and clicking on hide's triangle at the top level, the selected row remains visible until the mouse is clicked elsewhere.
The strange thing is that the problem occurs only in the ranks of the second rank, that is, the children of the children,and so on more inside, and it does not occur in the case of choosing a direct son for the row.
![Peek 2020-06-10 00-43](https://user-images.githubusercontent.com/13304792/84211760-069cdc80-aab4-11ea-88b9-e2ffa3ede052.gif)

**Comment by phase1geo** [comment]
I have seen that as well. I should have this fixed shortly.

**Comment by phase1geo** [comment]
This issue should be fixed in the devel branch and will be generally available in the next stable release.
