### ISSUE TITLE
Auto save not working

### ISSUE THREAD

**Issue by wada3n** [phase1geo/Outliner#56]
While using the latest version of the devel branch
Autosave is no longer working
After making some changes and exiting the application and then opening it again I can't find the last changes!

**Comment by phase1geo** [comment]
I'm not seeing any problems with auto-save.  What edits did you make exactly before exiting the application. I would like to reproduce the problem on my end so that I can fix it.

**Comment by wada3n** [comment]
It was working fine, after I built the new version the problem occurred.
All recent modifications go and I can't find it after reopening the app.
The experience was made in both Ubuntu and Elementary os.

![Peek 2020-07-03 22-36](https://user-images.githubusercontent.com/13304792/86498498-fb209680-bd7d-11ea-9271-7c388d5e3dd5.gif)

**Comment by phase1geo** [comment]
I can reproduce this issue.  I'll get a fix put together shortly.

**Comment by phase1geo** [comment]
This issue has been fixed in the devel branch and will be generally available in the next stable release.

**Comment by phase1geo** [comment]
FYI, the issue was not that the data wasn’t saved, it was just not being properly reloaded when the application was restarted, so no loss of data.

**Comment by wada3n** [comment]
Ah, I realized that when I opened yesterday's file and found it with modifications as it should be, so it is a reload issue!
Thanks a lot for the tip.
