### ISSUE TITLE
Use Granite.markup_accel_tooltip

### ISSUE THREAD

**Issue by cassidyjames** [phase1geo/Outliner#6]
It looks like you have your own method for making accel tooltips:

https://github.com/phase1geo/Outliner/blob/916c47249fdd34dca65d6fdadcf556a5d7ef7e5d/src/Utils.vala#L96-L99

However, this is built into Granite. Using the Granite version will ensure you get any bugfixes, style improvements, etc. as well as consistent key naming with other elemenary apps.

See: https://valadoc.org/granite/Granite.markup_accel_tooltip.html

**Comment by phase1geo** [comment]
I have updated the code base in the master branch to comply with this request.

**Comment by phase1geo** [comment]
Stable release 1.0.3 contains the fix for this issue.  Closing bug.
