### ISSUE TITLE
Suggestions for improved keyboard navigation: ENTER

### ISSUE THREAD

**Issue by dagelf** [phase1geo/Outliner#61]
Not sure where to discuss this, so hope it's fine leaving it here!

- I think ENTER should edit current row. ENTER inside current row should move on to a next row - otherwise there is no way to edit a row without using the mouse

**Comment by phase1geo** [comment]
The current row can be edited by using the 'e' key when a row is selected.

**Comment by dagelf** [comment]
Almost vim compatible 😜 We can probably leave that for those who are already used to it - I will try to add this functionality to make this a bit more consistent with other apps.
