### ISSUE TITLE
TAB and Shift-TAB missing from F1 Help Page

### ISSUE THREAD

**Issue by dagelf** [phase1geo/Outliner#62]
Not sure where to discuss this, so hope it's fine leaving it here!

- There is no mention of TAB in the help!! It took me a while to figure out, after trying ctrl-right and ctrl-left etc. Shift tab should also be mentioned

**Comment by phase1geo** [comment]
I will get this fixed in the next release.

**Comment by dagelf** [comment]
Already done! https://github.com/phase1geo/Outliner/pull/67

**Comment by dagelf** [comment]
Todo: Translations still needed

**Comment by phase1geo** [comment]
The master branch has been updated for this change.
