### ISSUE TITLE
Click and drag behaviour inconsistent

### ISSUE THREAD

**Issue by dagelf** [phase1geo/Outliner#66]
Good UI design requires action consistency. 

When clicking and dragging to re-order nodes, if you accidentally click on text, the functionality doesn't work - and edit mode is entered instead. If click-and-drag could be detected and the edit mode skipped and drag behavior executed then it would greatly improve usability.

**Comment by dagelf** [comment]
@phase1geo I really love your apps! I just discovered Vala last week, so I am hoping to submit pull requests for all the issues I raised... with your go-ahead of course. Thanks & Regards!

**Comment by phase1geo** [comment]
I want Outliner to be a text-first editing application.  Therefore, if the user clicks anywhere within the text or begins dragging anywhere within the text, the text should be operated on immediately.  This eliminates having to double-click on a row to edit a selected row or some other second event.

To drag rows with the cursor, dragging anywhere on the row that is not populated by text can be used to drag the row.

I don't view this as UI inconsistency but more of a design choice.  I suppose there are alternative ways to implement this, but Outliner's text-first approach to editing is important to me.

**Comment by dagelf** [comment]
Agreed... if there is no way to distinguish click-drag from click, without a double click, then this is a no-go. First is to see if this is possible, if not maybe Ctrl+click for drag then?

**Comment by phase1geo** [comment]
Control+clicking on a URL within text will launch a browser to display the associated webpage, FYI.
