### ISSUE TITLE
Stuck Activity Animation

### ISSUE THREAD

**Issue by dagelf** [phase1geo/Outliner#68]
Latest git version - this stays on my screen

![2020-12-09-083012_640x305_scrot](https://user-images.githubusercontent.com/802628/101593548-c7b2f980-39f8-11eb-948e-51680a1bdf54.png)

**Comment by phase1geo** [comment]
Yes, that is a known issue with newer versions of Gtk.  I'm still running elementary OS Hera which is based on Gtk 3.22.  Until I can get access to Odin, I cannot replicate this problem.

If you want to take a look into this issue on your end, that would be helpful.  The same issue resides within Minder as well.

**Comment by phase1geo** [comment]
I believe that this issue should be fixed with the 1.5.1 Flatpak.  Feel free to reopen this issue if this statement is incorrect.
