### ISSUE TITLE
unexpected behavior when row is collapsed

### ISSUE THREAD

**Issue by jaslar** [phase1geo/Outliner#69]
I create a row
   I press return for first child
   I press return for the second child
   I collapse the first row
   While collapsed, I press return, and get a child inserted before the first child
   I press return to get a child after the newly inserted one
   At that point, the previous row disappears
![image](https://user-images.githubusercontent.com/50773940/109702616-b2f68580-7b51-11eb-9095-7a1f7850547f.png)

Aside from the display issue, it seems like when I add rows after collapsing, I went the new text to follow all the children, to be a sibling of the first line, not an inserted child. Is this action, the way it is now, intentional? I would argue that the insert new child should only happen when the rows are expanded.

**Comment by phase1geo** [comment]
I have fixed this issue in the master branch.  The proper behavior should have been to add the new row as a sibling of the collapsed selected row.

**Comment by jaslar** [comment]
Yes, that seems to work. thanks! New problem, although I'll start a new issue.
