### ISSUE TITLE
Change requested for AppCenter: AppData formatting

### ISSUE THREAD

**Issue by cassidyjames** [phase1geo/Outliner#7]
You can't nest lists inside of paragraphs

https://github.com/phase1geo/Outliner/blob/916c47249fdd34dca65d6fdadcf556a5d7ef7e5d/data/com.github.phase1geo.outliner.appdata.xml#L19-L36

See: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description

**Comment by phase1geo** [comment]
I have updated the appdata.xml file to comply with the specification in the master branch.

**Comment by phase1geo** [comment]
Release 1.0.3 contains the fix.  Closing bug.
