### ISSUE TITLE
Package as Flatpak for elementary OS 6

### ISSUE THREAD

**Issue by danrabbit** [phase1geo/Outliner#77]
As you might have heard, AppCenter is going Flatpak! For elementary OS 6, we will not longer be accepting Debian packaging, so your app will need to be updated.

We have documentation on our developer guide for writing your Flatpak manifest here: https://docs.elementary.io/develop/writing-apps/our-first-app/packaging#flatpak-manifest

Also, in case you missed it, elementary OS 6 beta 2 is [now available](https://builds.elementary.io). This is a great time to get your app packaged up as Flatpak and test that everything is working before the final release. AppCenter submission for OS 6 will be open soon, so don't delay :)

**Comment by phase1geo** [comment]
There is an updated Flatpak in the master branch which is ready for Odin.

**Comment by danrabbit** [comment]
Right on! It looks like you're still using the `daily` version of the flatpak runtime, so you'll want to update that to the stable versiion `6` before publishing

I'm a little curious what you're using these permissions for?
```
  - '--filesystem=xdg-run/dconf'
  - '--talk-name=org.gnome.SettingsDaemon'
  - '--talk-name=ca.desrt.dconf'
  - '--env=DCONF_USER_CONFIG_DIR=.config/dconf'
```

**Comment by phase1geo** [comment]
I think that is some legacy options that no longer need to be there.

**Comment by phase1geo** [comment]
I have gone ahead and removed it from master.
