### ISSUE TITLE
Opens the same document twice

### ISSUE THREAD

**Issue by QWxleA** [phase1geo/Outliner#79]
Love the app! Built my own flatpak, which was a bit wonky, but that might be on my end (Fedora 34 - Gnome). The only "real" complaint I have is that it remembers the last open document. This in itself is not bad, except when I open the same document from my filemanager, now I have the same document twice.

This can lead to data loss, if you edit the one file, close it, and then the other one is auto-saved.

**Comment by phase1geo** [comment]
I have fixed this issue in the master branch.

**Comment by QWxleA** [comment]
Build latest flatpak from master, confirmed to work, thanks
