### ISSUE TITLE
Flatpak requests access to host filesystem

### ISSUE THREAD

**Issue by cassidyjames** [phase1geo/Outliner#81]
See:

https://github.com/phase1geo/Outliner/blob/84ab4718e4727e9ff034b2d05a8299bdce5f7719/com.github.phase1geo.outliner.yml#L7

In general, apps should only ask for access to as much as they need, and use Portals, e.g. via [FileChooserNative](https://valadoc.org/gtk+-3.0/Gtk.FileChooserNative.html). If your app does need access to files outside of a file chooser context, restricting it to the Documents folder may also make sense.

**Comment by phase1geo** [comment]
A new 1.5.1 release has been made which fixes this issue.
