### ISSUE TITLE
Adjusting zoom breaks visible font size

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Outliner#83]
1. Do some outlining
2. Change zoom to e.g. 125%
3. Create a new row, write some text there

The font size in that new row will look as if the zoom value was still at 100%. Changing zoom back to 100% and then again to 125% fixes it.

I'm guessing there's a missing canvas render update in there somewhere.

**Comment by phase1geo** [comment]
I have fixed this issue in the master branch.
