### ISSUE TITLE
Cyrillics exporting is broken

### ISSUE THREAD

**Issue by prokoudine** [phase1geo/Outliner#85]
Outliner saves non-Latin text in codes rather than human-readable letters, please see the attached test files.

[cyr-test.zip](https://github.com/phase1geo/Outliner/files/7206664/cyr-test.zip)

**Comment by phase1geo** [comment]
I still have some debug work to do on this issue, but if you enable Markdown in the properties menubutton and then export the document, you should get the correct output.

In the meantime, I will work on fixing this issue.

**Comment by phase1geo** [comment]
I have fixed this issue in the master branch.
