### ISSUE TITLE
Distribution Options

### ISSUE THREAD

**Issue by davidskeck** [phase1geo/Outliner#88]
Hello,

Are there plans to package this for distributions similar to Minder? I really would love to be able to use this on Pop!_OS and Zorin.

Thank you!

**Comment by phase1geo** [comment]
Minder is available as a Flatpak so that should allow it to run on any system.

**Comment by davidskeck** [comment]
I know Minder is but I'd like for Outliner to be one too.

**Comment by phase1geo** [comment]
Just found this after doing some web searching.  To add the elementary OS Flatpak repo to your system, try running the following command-line:

`flatpak remote-add --if-not-exists --system appcenter https://flatpak.elementary.io/repo.flatpakrepo`

You should be able to install Outliner with the command:

`flatpak install com.github.phase1geo.outliner`

**Comment by davidskeck** [comment]
Thanks. I've moved to a different tool since I didn't know this was available. I'll close this issue.
