### ISSUE TITLE
Save-Dialog seems broken.

### ISSUE THREAD

**Issue by crslp** [phase1geo/Outliner#89]
Just tested the app and I like it.
Sadly, when I wanted to save my document, it could not be saved to my home directory.
The save-dialog didn't list the existing home-folders like documents, downloads, etc.
The open-dialog seems to access the drive correctly.
I'm a bit pissed because my text is now gone.
Hopefully that issue is resolved quickly because the tool itself is very nice.

**Comment by phase1geo** [comment]
I'm assuming that you are using the Flatpak version of the app. If so, you will need to give it permissions to view your home folder in application portal. If you are running on elementary OS, you can change this in the settings panel under Applications.

**Comment by crslp** [comment]
That did the trick - thank you!
This step is somewhat annoying, tho.
Anyways, thanks again and thanks for the great tool!

**Comment by phase1geo** [comment]
Well, you only have to do it once. With that said, the next version of Outliner will change the default permissions to allow home directory access, so this step can be avoided.
